name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:

  standard:

    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

    defaults:
      run:
        shell: bash -l {0}

    name: "${{ matrix.runs-on }} • x64 ${{ matrix.args }}"
    runs-on: ${{ matrix.runs-on }}

    steps:

    - name: Basic GitHub action setup
      uses: actions/checkout@v2

    - name: Set conda environment
      if: runner.os != 'Windows'
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yaml
        environment-name: myenv

    - name: Set conda environment
      if: runner.os == 'Windows'
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        environment-file: environment.yaml
        activate-environment: test
        auto-activate-base: false

    - name: Configure using CMake
      run: cmake -Bbuild -DCMAKE_INSTALL_PREFIX:PATH="${CONDA_PREFIX}"

    - name: Install using CMake
      working-directory: build
      run: cmake --install .

    - name: Install using Python
      run: python -m pip install .

    - name: Compile example (using CMake)
      working-directory: example
      run: |
        cmake .
        cmake --build .

    - name: Compile example (using Python)
      run: |
        python setup.py build
        python setup.py install

    - name: Run example
      run: python main.py
